# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DailyGoals' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DailyGoals
  pod 'ReachabilitySwift', '~> 3'
  pod 'SVProgressHUD'
  pod 'SDWebImage'
  pod 'SwiftyJSON'

  target 'DailyGoalsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
